script:
  - swift package build benderbutler
  # - ls -al

after_failure:
  - echo "Failure"

after_script:
  - git add .
  - git log

config:
  to: veladan@me.com
  from: bender@veladan.org
  subject_bad: Error building benderbutler
  subject_ok: Build finished ok