#!/usr/bin/env ruby

require 'rake'

path = File.symlink?(__FILE__) ? File.readlink(__FILE__) : __FILE__
path = File.split(path)[0]

app = Rake.application
app.init
# do this as many times as needed
app.add_import path + '/Rakefile'
app.load_imports

app[ARGV[0]].invoke(ARGV.drop(1))
